name: cd
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }} # Required
          api_key: ${{ secrets.RENDER_API_KEY }} # Required
          wait_deploy: true # Optional, default: false
          github_deployment: true # Optional, default: false